### ISSUE TITLE
Voice demo doesn't seem to work

### ISSUE THREAD

**Issue by soft-boy** [fixie-ai/voice-demo#20]
[https://ai-jsx-voice.vercel.app/](https://ai-jsx-voice.vercel.app/)

tried cloning and running locally too... when I click, browser asks me for permission for mic. I'll speak but there's no response or anything. Is the demo on vercel supposed to work?

**Comment by juberti** [comment]
Hmm, yes, this demo uses an older version of our APIs and hasn't been updated yet...

**Comment by soft-boy** [comment]
a little confused... so just discovering you guys right now. are you sunsetting your APIs?

**Comment by juberti** [comment]
We're rebuilding our APIs around https://ultravox.ai, which will be more performant than the old SDK. Unfortunately you're catching us kind of in the middle of the transition, which I realize is inconvenient...

**Comment by soft-boy** [comment]
i figure this is not the place for customer support hehe, but how would I go about building a web/react app that streams ultravox? is it ready for that?

**Comment by juberti** [comment]
yeah, that's the kind of thing our new APIs will enable (rather than just the raw model weights). Check back in a week or so.

**Comment by juberti** [comment]
BTW, APIs are available as of last week: https://docs.google.com/forms/d/e/1FAIpQLSckzFiJ7_s_9jMpqgVGlKwCKjwxLh8yP8GLG_cdtJrXsM46Kg/viewform

**Comment by soft-boy** [comment]
Signed up :)
